services:
  backend:
    container_name: graphwrite-backend
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    # change ./backend/notes to where you want the note directory to be.
    volumes:
      - ./backend/notes:/app/notes
    restart: always

  frontend:
    container_name: graphwrite-frontend
    build: ./frontend
    ports:
      - "8080:80"
    restart: always